# Generated by Django 3.1.7 on 2021-04-05 23:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_viajes', '0002_favorito'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('lugar', 'de_quien')},
        ),
    ]
